# AWS S3 Resources
Resources:
  SoclessVault:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Name
          Value: Socless Vault
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Status: Enabled
            Prefix: one_day_temp/
  SoclessLogs:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Name
          Value: Socless Logs
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 365
            Status: Enabled
# Outputs
Outputs:
  SoclessVault:
    Description: Socless File Vault
    Value:
      Ref: SoclessVault
  SoclessLogs:
    Description: Socless Logs Vault
    Value:
      Ref: SoclessLogs
