import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';
import * as awsx from '@pulumi/awsx';
import { statesExeuctionRole } from './iam';
import { tagDeprecated } from './utils';

/**
 * @deprecated AwaitMessageResponseActivity as it it now deprecated infrastructure
 */
export const awaitMessageResponseActivity = new aws.sfn.Activity(
  '_socless_outbound_message_response',
  {
    tags: {
      ...tagDeprecated,
    },
  }
);

/**
 * @deprecated  TODO: Remove SaveMessageResponseTaskToken as it is now deprecated infrastructure
 */
export const saveMessageResponseTaskTokenMachine = new aws.sfn.StateMachine(
  'SaveMessageResponseTaskToken',
  {
    definition: JSON.stringify({
      Comment: 'Saves the Activity Token generated by _socless_await_slack_response',
      StartAt: 'StoreAwaitSlackResponseToken',
      States: {
        StoreAwaitSlackResponseToken: {
          Type: 'Task',
          Resource: '${SaveMessageResponseTokenLambdaFunction.Arn}',
          End: true,
        },
      },
    }),
    roleArn: statesExeuctionRole.arn,
    tags: {
      ...tagDeprecated,
    },
  }
);
